# Generated by Django 3.1 on 2023-12-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20231230_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_piad',
            new_name='amount_paid',
        ),
    ]
